services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      - FLASK_DEBUG=1
    
    volumes:
      - "~/.var/app/net.ankiweb.Anki/data/Anki2/User 1/collection.media/:/anki_media:z"
      - ./:/app:z

